
import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author felip
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        adminEmpleados ae = new adminEmpleados("./Empleados.adm");
        ae.cargarArchivo();
        DefaultComboBoxModel modelo = new DefaultComboBoxModel(ae.getListaEmpleados().toArray());
        
        CB_Empleados.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Empleados = new javax.swing.JPanel();
        TXT_CrearE = new javax.swing.JLabel();
        TXT_NameE = new javax.swing.JLabel();
        TF_NameE = new javax.swing.JTextField();
        TXT_AgeE = new javax.swing.JLabel();
        FF_AgeE = new javax.swing.JFormattedTextField();
        CreatE = new javax.swing.JToggleButton();
        TXT_CrearE1 = new javax.swing.JLabel();
        CB_Empleados = new javax.swing.JComboBox<>();
        DeleteE = new javax.swing.JButton();
        Carros = new javax.swing.JPanel();
        Simulacion = new javax.swing.JPanel();
        Tabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Bitacora = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TXT_CrearE.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TXT_CrearE.setText("CREAR EMPLEADO");

        TXT_NameE.setText("Nombre del empleado:");

        TXT_AgeE.setText("Edad:");

        FF_AgeE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        FF_AgeE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FF_AgeEActionPerformed(evt);
            }
        });

        CreatE.setText("Crear");
        CreatE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreatEMouseClicked(evt);
            }
        });

        TXT_CrearE1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TXT_CrearE1.setText("ELIMINAR EMPLEADO");

        DeleteE.setText("Eliminar");
        DeleteE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteEMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout EmpleadosLayout = new javax.swing.GroupLayout(Empleados);
        Empleados.setLayout(EmpleadosLayout);
        EmpleadosLayout.setHorizontalGroup(
            EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpleadosLayout.createSequentialGroup()
                .addGroup(EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmpleadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TXT_CrearE))
                    .addGroup(EmpleadosLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(TXT_NameE, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_NameE, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(TXT_AgeE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FF_AgeE, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EmpleadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TXT_CrearE1))
                    .addGroup(EmpleadosLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(CreatE, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmpleadosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CB_Empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(EmpleadosLayout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(DeleteE, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EmpleadosLayout.setVerticalGroup(
            EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpleadosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TXT_CrearE, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXT_NameE)
                    .addComponent(TF_NameE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_AgeE)
                    .addComponent(FF_AgeE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(CreatE)
                .addGap(92, 92, 92)
                .addComponent(TXT_CrearE1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CB_Empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(DeleteE)
                .addGap(52, 52, 52))
        );

        jTabbedPane1.addTab("Empleados", Empleados);

        javax.swing.GroupLayout CarrosLayout = new javax.swing.GroupLayout(Carros);
        Carros.setLayout(CarrosLayout);
        CarrosLayout.setHorizontalGroup(
            CarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        CarrosLayout.setVerticalGroup(
            CarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Carros", Carros);

        javax.swing.GroupLayout SimulacionLayout = new javax.swing.GroupLayout(Simulacion);
        Simulacion.setLayout(SimulacionLayout);
        SimulacionLayout.setHorizontalGroup(
            SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        SimulacionLayout.setVerticalGroup(
            SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Simulacion", Simulacion);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout TablaLayout = new javax.swing.GroupLayout(Tabla);
        Tabla.setLayout(TablaLayout);
        TablaLayout.setHorizontalGroup(
            TablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        TablaLayout.setVerticalGroup(
            TablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tabla", Tabla);

        javax.swing.GroupLayout BitacoraLayout = new javax.swing.GroupLayout(Bitacora);
        Bitacora.setLayout(BitacoraLayout);
        BitacoraLayout.setHorizontalGroup(
            BitacoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        BitacoraLayout.setVerticalGroup(
            BitacoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Bitacora", Bitacora);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FF_AgeEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FF_AgeEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FF_AgeEActionPerformed

    private void CreatEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreatEMouseClicked
        // TODO add your handling code here:
        Random r = new Random();
        
        Empleados e = new Empleados();
        
        String Nombre = TF_NameE.getText();
        String Age = FF_AgeE.getText();

        int Edad = Integer.parseInt(Age);
        if (Edad < 0){
            Edad = 1;
        }
        
        long id = 1+r.nextInt(1000);
        adminEmpleados ae = new adminEmpleados("./Empleados.adm");
        ae.cargarArchivo();
        ArrayList <Empleados> temp = ae.getListaEmpleados();
        for (int i = 0; i < temp.size(); i++) {
            if(id == temp.get(i).getId()){
                id = 1+r.nextInt(1000);
                i = 0;
            }
        }
        
        int exito = 0;
        
        e = new Empleados(Nombre, Edad, id, exito);
        
        
        ae.setEmpleado(e);
        ae.escribirArchivo();
        
        CB_Empleados.removeAll();
        DefaultComboBoxModel modelo = new DefaultComboBoxModel(ae.getListaEmpleados().toArray());
        
        CB_Empleados.setModel(modelo);
        TF_NameE.setText("");
        FF_AgeE.setText("");
    }//GEN-LAST:event_CreatEMouseClicked

    private void DeleteEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteEMouseClicked
        // TODO add your handling code here:
        int deleteE = CB_Empleados.getSelectedIndex();
        
        adminEmpleados ae = new adminEmpleados("./Empleados.adm");
        ae.cargarArchivo();
        ArrayList <Empleados> temp = ae.getListaEmpleados();
        temp.remove(deleteE);
        ae.setListaEmpleados(temp);
        ae.escribirArchivo();
        
        CB_Empleados.removeAll();
        DefaultComboBoxModel modelo = new DefaultComboBoxModel(ae.getListaEmpleados().toArray());
        
        CB_Empleados.setModel(modelo);
    }//GEN-LAST:event_DeleteEMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    ArrayList <Empleados> emp = new ArrayList();
    ArrayList <Carros> cars = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bitacora;
    private javax.swing.JComboBox<String> CB_Empleados;
    private javax.swing.JPanel Carros;
    private javax.swing.JToggleButton CreatE;
    private javax.swing.JButton DeleteE;
    private javax.swing.JPanel Empleados;
    private javax.swing.JFormattedTextField FF_AgeE;
    private javax.swing.JPanel Simulacion;
    private javax.swing.JTextField TF_NameE;
    private javax.swing.JLabel TXT_AgeE;
    private javax.swing.JLabel TXT_CrearE;
    private javax.swing.JLabel TXT_CrearE1;
    private javax.swing.JLabel TXT_NameE;
    private javax.swing.JPanel Tabla;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
